### ISSUE TITLE
Add sorting options for repositories (name, stars, last updated)

### ISSUE THREAD

**Issue by pray3m** [f0rsakeN-afk/githubinfo#1]
Currently, the project shows a user’s profile and their repos sorted by most stars by default. It would be awesome to have the option to sort by other criteria like name, stars, and last updated. This will help users find repos more easily based on what they’re looking for.

**Comment by f0rsakeN-afk** [comment]
Thanks for the feedback.
I'll incorporate sorting feature soon or you can also contribute if you want
